services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
    environment:
      - NODE_ENV=production
    networks:
      - zdravmost-network

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - zdravmost-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"  
    volumes:
      - redis_data:/data
    networks:
      - zdravmost-network

volumes:
  postgres_data:
  redis_data:

networks:
  zdravmost-network:
    driver: bridge
